caps, grammar, etc
amidaware/trmm-docs pull request #159
Opened 2023-05-07 20:40 UTC by bbrendon

Lots of tiny changes. Enjoy!! :)

2023-05-07 21:29 UTC, silversword411 requested changes
Tweak that, everything else looks good, thanks! :)

2023-05-07 21:29 UTC, silversword411 commented on docs/guide_gettingstarted.md
> +### Maintenance
These menu levels are there for the TOC to be arranged by:

Time Range
-> Categories in time range

<img width="264" alt="2023-05-07_172723 - brave_Getting_Started_Guide_-_Tactical_RMM_Documentation" src="https://user-images.githubusercontent.com/13395348/236703404-e27f5418-c839-4fb4-b575-dd039e005968.png">

I don't think making it a descending tree is the right layout.

Everything else looks good!

2023-05-08 00:28 UTC, bbrendon commented on docs/guide_gettingstarted.md
> +### Maintenance
I reverted the page

2023-05-08 11:39 UTC, silversword411 reviewed
Fixed outside review

2023-05-08 11:39 UTC, merged